name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Start server in background
        run: |
          node server.js & echo $! > .server.pid
          npx --yes wait-on http://localhost:3000
        env:
          CI: true

      - name: Run Puppeteer smoke test
        run: node mcp-smoke-test.js

      - name: Stop server
        if: always()
        run: kill $(cat .server.pid) || true
